services:
  rag:
    image: ghcr.io/davmacario/notes-rag:latest
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file: .env
    environment:
      NOTES_BRANCH: main
      NOTES_DIRECTORY: ./notes_cache
      REBUILD_CRON: "0 */6 * * *"
      TZ: Europe/Amsterdam
      LOG_LEVEL: "debug"
    ports:
      - "127.0.0.1:9099:9099"
    command:
      - --rebuild-on-start
